services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golfclub_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://qap3-db.c65d6esjg4f4.us-east-1.rds.amazonaws.com:3306/QAP3_API_DB
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: Keyin202!
